AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31

Resources:
  FastAPIProxyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "FastAPI"
          version: "1.0"
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses:
                default:
                  statusCode: "200"
                  responseParameters:
                    method.response.header.Access-Control-Allow-Origin: "'*'"
                    method.response.header.Access-Control-Allow-Methods: "'OPTIONS,GET,POST'"
                    method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FastAPILambdaFunction.Arn}/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"

  FastAPILambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 10
      MemorySize: 128
      EphemeralStorage:
        Size: 512
      ReservedConcurrentExecutions: 10
      Policies: AWSLambdaBasicExecutionRole
      Events:
        FastAPIProxy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: FastAPIProxyApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./lambda
      DockerTag: fastapi-lambda


Outputs:
  ApiEndpoint:
    Description: "URL do endpoint da API Gateway"
    Value: !Sub "https://${FastAPIProxyApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
    Export:
      Name: ApiEndpoint

  LambdaFunctionArn:
    Description: "ARN da função Lambda"
    Value: !GetAtt FastAPILambdaFunction.Arn
    Export:
      Name: LambdaFunctionArn

  LambdaFunctionName:
    Description: "Nome da função Lambda"
    Value: !Ref FastAPILambdaFunction
    Export:
      Name: LambdaFunctionName